name: 'package-vulnerability-detector'
description: 'Find vulnerabilities in packages listed by the SBOM generator'
branding:
  icon: 'check-circle'
  color: 'green'
inputs: 
runs:
  using: "composite"
  steps:  
    - name: Change sbom
      run: (tail -n +2 sobs.xml)>sbom-new.txt
      shell: bash
    - name: Auth detector script
      run: chmod -x script.sh
      shell: bash
    - name: Run detector script
      run: .github-actions-for-cicd/package-vulnerability-detector/script.sh
      shell: bash
 
